# Generated by Django 5.2 on 2025-06-09 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Úkol')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('ocekavane', models.DateField(blank=True, null=True, verbose_name='Očekávaný termín')),
                ('predmet', models.CharField(blank=True, max_length=100, verbose_name='Předmět')),
                ('done', models.BooleanField(default=False, verbose_name='Splněno')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno')),
                ('deleted', models.BooleanField(default=False, verbose_name='Smazáno')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Smazáno v')),
            ],
        ),
    ]
