# Generated by Django 5.1.6 on 2025-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamestnanci', '0002_alter_employee_empno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mgr',
        ),
        migrations.AlterField(
            model_name='department',
            name='deptno',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
